/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'jresendiz' at '10/23/16 8:48 PM' with Gradle 2.14.1
 *
 * @author jresendiz, @date 10/23/16 8:48 PM
 */
class SimpleChat {
    
}
