package com.nearsoft.jresendiz;

import io.vertx.groovy.ext.web.Router
import io.vertx.groovy.ext.web.handler.StaticHandler
import io.vertx.groovy.core.http.HttpServer
import io.vertx.lang.groovy.GroovyVerticle

/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'jresendiz' at '10/23/16 8:48 PM' with Gradle 2.14.1
 *
 * @author jresendiz, @date 10/23/16 8:48 PM
 */

class SimpleChat extends GroovyVerticle {
    HttpServer server;
    Router router;

    public void start() {
        // This method is called whenever you create a verticle
        server = vertx.createHttpServer()

        router = Router.router(vertx)
        router.route().handler(StaticHandler.create())

        server.requestHandler(router.&accept).listen(8080)
    }

    public void stop() {
        // This method is called whenever a verticle is closed or dies
        System.err.println("Verticle has been closed!")
    }

}
